"""initial schema."""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

import ziggy.models

if TYPE_CHECKING:
    from collections.abc import Sequence


revision: str = "6b519c405276"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("scheme", sa.String(length=5), nullable=False),
        sa.Column("include_subdomains", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("configured_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("deactivated_at", ziggy.models.UtcDateTime(length=32), nullable=True),
        sa.CheckConstraint("scheme IN ('http', 'https')", name="ck_domains_scheme"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host"),
    )
    with op.batch_alter_table("domains", schema=None) as batch_op:
        batch_op.create_index("ix_domains_active", ["active"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("window_start", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("window_end", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("generated_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("discovered_count", sa.Integer(), nullable=False),
        sa.Column("archived_count", sa.Integer(), nullable=False),
        sa.Column("outstanding_count", sa.Integer(), nullable=False),
        sa.Column("active_domain_count", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "DELIVERED",
                "LOGGED",
                "FAILED",
                name="reportstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at", ziggy.models.UtcDateTime(length=32), nullable=False
        ),
        sa.Column("delivered_at", ziggy.models.UtcDateTime(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("discord_message_id", sa.String(length=32), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=32), nullable=True),
        sa.Column("discord_webhook_id", sa.String(length=32), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column(
            "lease_expires_at", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("window_start", "window_end", name="uq_reports_window"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reports_pending",
            ["state", "next_attempt_at", "lease_expires_at"],
            unique=False,
        )

    op.create_table(
        "service_state",
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("heartbeat_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column(
            "last_report_window_end", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("discovered_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("discovered_from_id", sa.Integer(), nullable=True),
        sa.Column(
            "first_crawled_at", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.Column(
            "last_crawled_at", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.Column("next_crawl_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column(
            "next_archive_at", ziggy.models.UtcDateTime(length=32), nullable=False
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sitemap_depth", sa.Integer(), nullable=False),
        sa.Column("crawl_attempts", sa.Integer(), nullable=False),
        sa.Column("crawl_lease_owner", sa.String(length=36), nullable=True),
        sa.Column(
            "crawl_lease_expires_at", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.Column("archive_lease_owner", sa.String(length=36), nullable=True),
        sa.Column(
            "archive_lease_expires_at",
            ziggy.models.UtcDateTime(length=32),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["discovered_from_id"], ["pages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.create_index("ix_pages_domain", ["domain_id"], unique=False)
        batch_op.create_index(
            "ix_pages_due_archive",
            ["next_archive_at", "archive_lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_pages_due_crawl",
            ["next_crawl_at", "crawl_lease_expires_at"],
            unique=False,
        )

    op.create_table(
        "archive_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("parent_job_id", sa.String(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("DIRECT", "OUTLINK", name="archivejobkind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "INTENT",
                "UNCERTAIN",
                "SUBMITTED",
                "PENDING",
                "RATE_LIMITED",
                "SUCCEEDED",
                "FAILED",
                name="archivejobstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("cycle_key", sa.String(length=255), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column("intent_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("submitted_at", ziggy.models.UtcDateTime(length=32), nullable=True),
        sa.Column("completed_at", ziggy.models.UtcDateTime(length=32), nullable=True),
        sa.Column(
            "next_attempt_at", ziggy.models.UtcDateTime(length=32), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("service_code", sa.String(length=255), nullable=True),
        sa.Column("saved_to_my_archive", sa.Boolean(), nullable=False),
        sa.Column("outlinks_processed", sa.Boolean(), nullable=False),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column(
            "lease_expires_at", ziggy.models.UtcDateTime(length=32), nullable=True
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_job_id"], ["archive_jobs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cycle_key"),
        sa.UniqueConstraint("external_job_id"),
    )
    with op.batch_alter_table("archive_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_archive_jobs_due",
            ["state", "next_attempt_at", "lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_archive_jobs_external_active",
            ["external_job_id", "state"],
            unique=False,
        )
        batch_op.create_index("ix_archive_jobs_page", ["page_id"], unique=False)
        batch_op.create_index(
            "uq_archive_jobs_active_direct_page",
            ["page_id"],
            unique=True,
            sqlite_where=sa.text(
                "kind = 'DIRECT' AND state IN "
                "('INTENT', 'UNCERTAIN', 'SUBMITTED', 'PENDING', 'RATE_LIMITED')"
            ),
        )

    op.create_table(
        "captures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("archive_job_id", sa.String(length=36), nullable=False),
        sa.Column("captured_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.Column("wayback_url", sa.Text(), nullable=False),
        sa.Column("screenshot", sa.Text(), nullable=True),
        sa.Column("completed_at", ziggy.models.UtcDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_job_id"], ["archive_jobs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("archive_job_id"),
        sa.UniqueConstraint(
            "page_id", "captured_at", name="uq_captures_page_timestamp"
        ),
    )
    with op.batch_alter_table("captures", schema=None) as batch_op:
        batch_op.create_index(
            "ix_captures_page_captured", ["page_id", "captured_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("captures", schema=None) as batch_op:
        batch_op.drop_index("ix_captures_page_captured")

    op.drop_table("captures")
    with op.batch_alter_table("archive_jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_archive_jobs_active_direct_page",
            sqlite_where=sa.text(
                "kind = 'DIRECT' AND state IN "
                "('INTENT', 'UNCERTAIN', 'SUBMITTED', 'PENDING', 'RATE_LIMITED')"
            ),
        )
        batch_op.drop_index("ix_archive_jobs_page")
        batch_op.drop_index("ix_archive_jobs_external_active")
        batch_op.drop_index("ix_archive_jobs_due")

    op.drop_table("archive_jobs")
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_index("ix_pages_due_crawl")
        batch_op.drop_index("ix_pages_due_archive")
        batch_op.drop_index("ix_pages_domain")

    op.drop_table("pages")
    op.drop_table("service_state")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_pending")

    op.drop_table("reports")
    with op.batch_alter_table("domains", schema=None) as batch_op:
        batch_op.drop_index("ix_domains_active")

    op.drop_table("domains")
    # ### end Alembic commands ###
